### ISSUE TITLE
Update mod to work on most recent ADOFAI version

### ISSUE THREAD

**Issue by Hallunacy** [thijnmens/AdofaiWeb#3]
Hey! Saw this mod and thought using it to make an overlay would be really cool-- but it's broken on the recent versions of ADOFAI. Is there any possibility of an update? 🥺👉👈

**Comment by thijnmens** [comment]
I'll look into it, i haven't played adofai for a while so i didn't notice it was broken. Expect an update somewhere this week 👍

**Comment by thijnmens** [comment]
Quick update, i am looking through this code and i should be ashamed of every publishing this (yes it's that bad). I am going to rewrite the mod. My estimation is that i will finish it within 48 hours from now. While I'm at it I'll also update the documentation to make creating layouts a bit easier

**Comment by thijnmens** [comment]
Alrighty another update, It took a bit longer because of my regular day-to-day job among other things, but i think this is working well enough for a release. I am going to update the wiki now with all the new info, then i update the example theme and at least make a release to the discord (and here on github)

**Comment by Hallunacy** [comment]
Yippee

**Comment by thijnmens** [comment]
I've created a [pre-release](https://github.com/thijnmens/AdofaiWeb/releases/tag/v2.0.0-beta) for the mod. The reason it's not a full release is because i still wish to add some basic functionality that it's currently missing (some stats like checkpoints, deaths, tries, etc). You can use this release to start with your layout however. Details on how can be found on the [wiki](https://github.com/thijnmens/AdofaiWeb/wiki)

**Comment by Hallunacy** [comment]
Is there any new documentation on installing/using the mod? I'm having trouble getting it to work. I've moved my install directory to the C drive & added the Atom theme to my OBS browser sources jic the old themes used outdated code-- but it still won't function.

**Comment by thijnmens** [comment]
Yeah, the atom theme currently does not update any data however so maybe it appears as if it's not working but it actually is. you can test by going to <https://livepersoninc.github.io/ws-test-page/>, entering `ws://localhost:4444` as the URL and pressing connect. If it connects and recieves data on game input it's working. If it can't connect then something is wrong and you can refer to [this](https://github.com/thijnmens/AdofaiWeb/wiki/Setting-up-AdofaiWeb) wiki page

**Comment by Hallunacy** [comment]
Yeah I just noticed that, my bad. It does properly send data though, so it's working as intended!

**Comment by thijnmens** [comment]
Good to hear! I should've specified the situation with atom being a WIP better. In any case I'll see what i can do with the missing data (checkpoints, deaths, etc)
